#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr();

	int num;
	char alpha;
	char str[30];
	float flt;

	cout << "\nEnter any no.:";
	cin >> num;

	cout << "\nEnter any character: ";
	cin >> alpha;

	cout << "\nEnter any string: ";
	cin >> str;

	cout << "\nEnter any float: ";
	cin >> flt;

	cout << "\nInteger: " << num;
	cout << "\nCharacter: " << alpha;
	cout << "\nString: " << str;
	cout << "\nFloat: " << flt;

	getch();
}






















