#include<iostream.h>
#include<conio.h>
void main()
{
int a,b,c;
clrser();
cout<<"\n *** ARITHMETIC PROGRAM ***\n";
cout<<"\n ENTER THE FIRST NUMBER:";
cin>>a;
cout<<"\n ENTER THE SECOND NUMBER:";
cin>>b;
c=a+b;
cout<<"\n THE ADDITION OF TWO NEUMBER:"<<c;
c=a-b;
cout<<"\n THE SUBSTRACTION OF TWO NUMBER:"<<c;
c=a*b;
cout<<"\n THE MULTIPLCATION OF TWO NUMBER:"<<c;
c=a/b;
cout<<"\n THE DIVISION OF TWO NUMBER:"<<c;
getch();
}